name: Global Animal Adoptions Bot

on:
  schedule:
    - cron: "*/5 * * * *"  # ogni 5 minuti
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Restore ads.db cache
        uses: actions/cache@v3
        with:
          path: ads.db
          key: adsdb-v1    
    
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python main.py

      - name: Save ads.db cache
        uses: actions/cache@v3
        with:
          path: ads.db
          key: adsdb-v1
  
